main <- function(path) {
  melodiesList <- list()
  melodiesTable <- read.csv(path, sep=",")
  len <- length(melodiesTable$Melody.name)
  for(i in 1:len) {
    melodiesList[i] <- strsplit(as.character(melodiesTable$Melody[[i]]), "[ ]")
  }
  print("-----------------------------------------------------------")
  print("Melodies list:")
  print("-----------------------------------------------------------")
  print(melodiesList)
  matricesList <- makeMatrices(melodiesList)
  print("-----------------------------------------------------------")
  print("Adjacency matrices (A) for melodies, respectively:")
  print("-----------------------------------------------------------")
  print(matricesList)
  eigensList <- calcEigens(matricesList)
  print("-----------------------------------------------------------")
  print("Matrices spectra, respectively")
  print("-----------------------------------------------------------")
  print(eigensList)
  print("-----------------------------------------------------------")
  print("Euclidean distances, respectively:")
  print("-----------------------------------------------------------")
  distanceMatrix <- calcDistances(melodiesTable$Melody.name, eigensList)
  print("-----------------------------------------------------------")
  print("Cluster analysis:")
  print("-----------------------------------------------------------")
  calcClusters(melodiesTable, distanceMatrix, eigensList)
  makeGraphs(matricesList)
  
}